Repository IvanMurzak/Unity-MCP, pull requests merged in 2025-04, with the labels that each got.

#13 AOT Support
  Assets/root/Runtime/com.IvanMurzak.Unity.MCP.Runtime.asmdef
  Assets/root/Runtime/link.xml
  Assets/root/Runtime/link.xml.meta
  Assets/root/Server/com.IvanMurzak.Unity.MCP.Server.asmdef
  Assets/root/Tests/Editor/com.IvanMurzak.Unity.MCP.Editor.Tests.asmdef
  Assets/root/Tests/Runtime/com.IvanMurzak.Unity.MCP.Tests.asmdef
Labels: enhancement

#14 Command - Component.Add
  Assets/root/Editor/Scripts/API/Tool/Component.Add.cs
  Assets/root/Editor/Scripts/API/Tool/Component.Add.cs.meta
  Assets/root/Editor/Scripts/Startup.Server.cs
  Assets/root/Editor/Scripts/Startup.cs
  Assets/root/Editor/Scripts/UI/MenuItems.cs
  Assets/root/Editor/Scripts/Utils.meta
  Assets/root/Editor/Scripts/Utils/ProcessUtils.cs
  Assets/root/Editor/Scripts/Utils/ProcessUtils.cs.meta
  Assets/root/Runtime/Utils/MainThread.Editor.cs
  Assets/root/Server/API/Tool/Component.Add.cs
  Assets/root/Server/API/Tool/Component.Add.cs.meta
  Assets/root/Server/API/Tool/GameObject.Create.cs
  Assets/root/Server/API/Tool/GameObject.Delete.cs
  Assets/root/Server/Common/Utils/DirectoryUtils.cs
  Assets/root/Server/Common/Utils/ErrorUtils.cs
  Assets/root/Server/Common/Utils/ErrorUtils.cs.meta
  UserSettings/Layouts/default-2022.dwlt
Labels: enhancement

#18 Add GitHub Actions workflows for Unity 2022.3.61f1
  .github/workflows/2022.3.61f1_editmode.yml
  .github/workflows/2022.3.61f1_playmode.yml
  .github/workflows/2022.3.61f1_standalone.yml
Labels: enhancement

#19 Add GitHub Actions workflows for Unity 6000.0.46f1
  .github/workflows/6000.0.46f1_editmode.yml
  .github/workflows/6000.0.46f1_playmode.yml
  .github/workflows/6000.0.46f1_standalone.yml
Labels: enhancement

#20 Updated MCP C# SDK to version 0.1.0-preview.8
  Assets/root/Server/Common/Data/Request/Tool/Call/IRequestCallTool.cs
  Assets/root/Server/Common/Data/Request/Tool/Call/RequestCallTool.cs
  Assets/root/Server/Common/Runner/Tool/IRunTool.cs
  Assets/root/Server/Common/Runner/Tool/RunTool.cs
  Assets/root/Server/Common/Utils/RequestCallToolExtensions.cs
  Assets/root/Server/com.IvanMurzak.Unity.MCP.Server.csproj
Labels: enhancement

#32 Tool: Find GameObject by name
  Assets/root/Editor/Scripts/API/Resource/GameObject.Hierarchy.cs
  Assets/root/Editor/Scripts/API/Tool/Component.GetAll.cs
  Assets/root/Editor/Scripts/API/Tool/Component.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.AddComponent.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.AddComponent.cs.meta
  Assets/root/Editor/Scripts/API/Tool/GameObject.Create.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.Destroy.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.FindByName.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.FindByName.cs.meta
  Assets/root/Editor/Scripts/API/Tool/GameObject.cs
  Assets/root/Editor/Scripts/Utils/GameObjectUtils.cs
  Assets/root/Runtime/Utils/MainThread.Editor.cs
  Assets/root/Server/Common/Attribute/Prompt/McpPluginPromptArgumentAttribute.cs
  Assets/root/Server/Common/Attribute/Prompt/McpPluginPromptArgumentAttribute.cs.meta
  Assets/root/Server/Common/Attribute/Prompt/McpPluginPromptAttribute.cs
  Assets/root/Server/Common/Attribute/Prompt/McpPluginPromptAttribute.cs.meta
  Assets/root/Server/Common/Attribute/Prompt/McpPluginPromptTypeAttribute.cs
  Assets/root/Server/Common/Attribute/Prompt/McpPluginPromptTypeAttribute.cs.meta
  Assets/root/Server/Common/Attribute/Resources/McpPluginResourceAttribute.cs
  Assets/root/Server/Common/Attribute/Resources/McpPluginResourceAttribute.cs.meta
  Assets/root/Server/Common/Attribute/Resources/McpPluginResourceTypeAttribute.cs
  Assets/root/Server/Common/Attribute/Resources/McpPluginResourceTypeAttribute.cs.meta
  Assets/root/Server/Common/Attribute/Tool/McpPluginToolArgumentAttribute.cs
  Assets/root/Server/Common/Attribute/Tool/McpPluginToolArgumentAttribute.cs.meta
  Assets/root/Server/Common/Attribute/Tool/McpPluginToolAttribute.cs
  Assets/root/Server/Common/Attribute/Tool/McpPluginToolAttribute.cs.meta
  Assets/root/Server/Common/Attribute/Tool/McpPluginToolTypeAttribute.cs
  Assets/root/Server/Common/Attribute/Tool/McpPluginToolTypeAttribute.cs.meta
  Assets/root/Server/Common/McpPlugin/Builder/McpPluginBuilderExtensions.Prompt.cs
  Assets/root/Server/Common/McpPlugin/Builder/McpPluginBuilderExtensions.Resource.cs
  Assets/root/Server/Common/McpPlugin/Builder/McpPluginBuilderExtensions.Tool.cs
  Assets/root/Server/Server/API/Tool/GameObject.AddComponent.cs
  Assets/root/Server/Server/API/Tool/GameObject.AddComponent.cs.meta
  Assets/root/Server/Server/API/Tool/GameObject.FindByName.cs
  Assets/root/Server/Server/API/Tool/GameObject.FindByName.cs.meta
  Assets/root/Tests/Editor/TestGameObjectUtils.cs
  Assets/root/Tests/Editor/Tool.meta
  Assets/root/Tests/Editor/Tool/GameObject.meta
  Assets/root/Tests/Editor/Tool/GameObject/TestToolGameObject.cs
  Assets/root/Tests/Editor/Tool/GameObject/TestToolGameObject.cs.meta
Labels: enhancement

#34 Tool: GameObject.GetComponents
  Assets/root/Editor/Scripts/API/Tool/GameObject.GetComponents.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.GetComponents.cs.meta
  Assets/root/Server/Server/API/Tool/Component.GetAll.cs
  Assets/root/Server/Server/API/Tool/Component.cs
  Assets/root/Server/Server/API/Tool/GameObject.AddComponent.cs
  Assets/root/Server/Server/API/Tool/GameObject.Create.cs
  Assets/root/Server/Server/API/Tool/GameObject.Destroy.cs
  Assets/root/Server/Server/API/Tool/GameObject.FindByName.cs
  Assets/root/Server/Server/API/Tool/GameObject.FindByPath.cs
  Assets/root/Server/Server/API/Tool/GameObject.GetComponents.cs
  Assets/root/Server/Server/API/Tool/GameObject.GetComponents.cs.meta
  Assets/root/Server/Server/API/Tool/GameObject.cs
Labels: enhancement

#38 Tool: Assets.Prefab.Instantiate
  .github/workflows/main.yml
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.Instantiate.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.Create.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.Destroy.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.FindByName.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.FindByPath.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.GetComponents.cs
  Assets/root/Editor/Scripts/Utils/GameObjectUtils.cs
  Assets/root/Server/Common/Utils/StringUtils.cs
  Assets/root/Server/Common/Utils/StringUtils.cs.meta
  Assets/root/Server/Server/API/Tool/GameObject.AddComponent.cs
  Assets/root/Tests/Editor/TestGameObjectUtils.cs
  Assets/sample/Sample.unity
Labels: enhancement

#40 Tool: Scene.GetHierarchy
  .github/workflows/main.yml
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.Instantiate.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.cs
  Assets/root/Editor/Scripts/API/Tool/Component.GetAll.cs
  Assets/root/Editor/Scripts/API/Tool/Component.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.AddComponent.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.Destroy.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.FindByName.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.FindByPath.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.GetComponents.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.cs
  Assets/root/Editor/Scripts/API/Tool/Scene.GetHierarchy.cs
  Assets/root/Editor/Scripts/API/Tool/Scene.GetHierarchy.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Scene.cs
  Assets/root/Editor/Scripts/API/Tool/Scene.cs.meta
  Assets/root/Editor/Scripts/Unity/GameObjectMetadata.cs
  Assets/root/Editor/Scripts/Utils/GameObjectUtils.cs
  Assets/root/Editor/Scripts/Utils/SceneUtils.Editor.cs
  Assets/root/Editor/Scripts/Utils/SceneUtils.Editor.cs.meta
  Assets/root/Editor/Scripts/Utils/SceneUtils.cs
  Assets/root/Editor/Scripts/Utils/SceneUtils.cs.meta
  Assets/root/Server/Server/API/Tool/Scene.GetHierarchy.cs
  Assets/root/Server/Server/API/Tool/Scene.GetHierarchy.cs.meta
  Assets/root/Server/Server/API/Tool/Scene.cs
  Assets/root/Server/Server/API/Tool/Scene.cs.meta
Labels: enhancement

#41 Updated Tool: Scene.Hierarchy
  Assets/root/Editor/Scripts/API/Tool/GameObject.FindByName.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.FindByPath.cs
  Assets/root/Editor/Scripts/API/Tool/Scene.GetHierarchy.cs
  Assets/root/Editor/Scripts/Unity/GameObjectMetadata.cs
  Assets/root/Editor/Scripts/Unity/SceneMetadata.cs
  Assets/root/Editor/Scripts/Unity/SceneMetadata.cs.meta
  Assets/root/Editor/Scripts/Utils/GameObjectUtils.cs
  Assets/root/Editor/Scripts/Utils/SceneUtils.cs
  Assets/root/Server/Program.cs
  Assets/root/Server/Server/API/Tool/GameObject.FindByName.cs
  Assets/root/Server/Server/API/Tool/GameObject.FindByPath.cs
  Assets/root/Server/Server/API/Tool/Scene.GetHierarchy.cs
Labels: enhancement

#42 Fixed NLog Server integration
  Assets/root/Server/Common/Utils/StringUtils.cs
  Assets/root/Server/NLog.config
  Assets/root/Server/com.IvanMurzak.Unity.MCP.Server.csproj
Labels: bug

#51 Tool: Assets.Refresh
  Assets/Resources/Unity-MCP-ConnectionConfig.json
  Assets/root/Editor/Scripts/API/Tool/Assets.Refresh.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Refresh.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Assets.Search.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.cs.meta
  Assets/root/Server/Server/API/Tool/Assets.Assets.Refresh.cs
  Assets/root/Server/Server/API/Tool/Assets.Assets.Refresh.cs.meta
  Assets/root/Server/Server/API/Tool/Assets.Assets.Search.cs
  Assets/root/Server/Server/API/Tool/Assets.Assets.cs
  Assets/root/Server/Server/API/Tool/Assets.Assets.cs.meta
  Assets/root/Server/Server/Routing/Tool/ToolRouter.Call.cs
Labels: enhancement

#54 Support modifying references to `UnityEngine.Object` instances
  Assets/Resources/Unity-MCP-ConnectionConfig.json
  Assets/root/Editor/Scripts/API/Tool/Assets.Load.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Load.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Assets.Refresh.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Search.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.GetComponents.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.ModifyComponent.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.cs
  Assets/root/Runtime/Utils/Serializer.Component.cs
  Assets/root/Server/Common/Data/Utils/InstanceId.cs
  Assets/root/Server/Common/Utils/Json/Converter/InstanceIdConverter.cs
  Assets/root/Server/Common/Utils/Json/JsonUtils.cs
  Assets/root/Server/Server/API/Tool/Assets.Load.cs
  Assets/root/Server/Server/API/Tool/Assets.Load.cs.meta
  Assets/root/Server/Server/API/Tool/Assets.Refresh.cs
  Assets/root/Server/Server/API/Tool/Assets.Refresh.cs.meta
  Assets/root/Server/Server/API/Tool/Assets.Search.cs
  Assets/root/Server/Server/API/Tool/Assets.Search.cs.meta
  Assets/root/Server/Server/API/Tool/Assets.cs
  Assets/root/Server/Server/API/Tool/Assets.cs.meta
  Assets/root/Server/Server/API/Tool/GameObject.GetComponents.cs
  Assets/root/Server/Server/API/Tool/GameObject.ModifyComponent.cs
Labels: enhancement

#57 fix: Server source code not found in Unity Package (Unity 6000.+)
  Assets/root/Editor/Scripts/Startup.Server.cs
  Assets/root/package.json
Labels: enhancement

#59 fix: NullReferenceException in Assets.Prefab.Instantiate
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.Instantiate.cs
Labels: bug

#61 Truncating long Scene.GetHierarchy response by 500 objects
  Assets/root/Editor/Scripts/API/Tool/Scene.GetHierarchy.cs
  Assets/root/Editor/Scripts/Unity/GameObjectMetadata.cs
  Assets/root/Editor/Scripts/Unity/SceneMetadata.cs
  Assets/root/Server/Common/Utils/Consts.RPC.cs
  Assets/root/Server/Common/Utils/Consts.cs
  Assets/root/Server/Server/Hub/BaseHub.cs
  Assets/root/Server/Server/Hub/RemoteApp.cs
  Assets/root/Server/Server/Routing/Tool/ToolRouter.Call.cs
Labels: bug

#66 docs: update README.md
  README.md
Labels: documentation

#67 Tool: Editor.GetApplicationInformation + Editor.SetApplicationState
  Assets/root/Editor/Scripts/API/Tool/Editor.GetApplicationInformation.cs
  Assets/root/Editor/Scripts/API/Tool/Editor.GetApplicationInformation.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Editor.SetApplicationState.cs
  Assets/root/Editor/Scripts/API/Tool/Editor.SetApplicationState.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Editor.cs
  Assets/root/Editor/Scripts/API/Tool/Editor.cs.meta
  Assets/root/Server/.vscode/tasks.json
  Assets/root/Server/Server/API/Tool/Editor.GetApplicationInformation.cs
  Assets/root/Server/Server/API/Tool/Editor.GetApplicationInformation.cs.meta
  Assets/root/Server/Server/API/Tool/Editor.SetApplicationState.cs
  Assets/root/Server/Server/API/Tool/Editor.SetApplicationState.cs.meta
  Assets/root/Server/Server/API/Tool/Editor.cs
  Assets/root/Server/Server/API/Tool/Editor.cs.meta
  Assets/sample/Sample.unity
Labels: enhancement

#68 Rebuild server if newer version is available in the package source
  Assets/root/Editor/Scripts/Startup.Server.cs
  Assets/root/Editor/Scripts/Startup.cs
  Assets/root/Server/Common/Utils/FileUtils.cs
  Assets/root/Server/com.IvanMurzak.Unity.MCP.Server.csproj
  Assets/root/Server/version
  Assets/root/Server/version.meta
Labels: enhancement

#71 Tool: GameObject.Duplicate + GameObject.SetParent + Assets.Move + Assets.Copy + Assets.Delete + Assets.CreateFolders + Editor.Selection.Get + Editor.Selection.Set
  Assets/root/Documentation~/README.md
  Assets/root/Editor/Scripts/API/Tool/Assets.Copy.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Copy.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Assets.CreateFolders.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.CreateFolders.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Assets.Delete.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Delete.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Assets.Load.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Move.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Move.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Assets.cs
  Assets/root/Editor/Scripts/API/Tool/Editor.Selection.Get.cs
  Assets/root/Editor/Scripts/API/Tool/Editor.Selection.Get.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Editor.Selection.Set.cs
  Assets/root/Editor/Scripts/API/Tool/Editor.Selection.Set.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Editor.Selection.cs
  Assets/root/Editor/Scripts/API/Tool/Editor.Selection.cs.meta
  Assets/root/Editor/Scripts/API/Tool/GameObject.Duplicate.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.Duplicate.cs.meta
  Assets/root/Editor/Scripts/API/Tool/GameObject.SetParent.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.SetParent.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Script.Delete.cs
  Assets/root/Editor/Scripts/API/Tool/Script.UpdateOrCreate.cs
  Assets/root/README.md
  Assets/root/Server/Common/Utils/ObjectUtils.cs
  Assets/root/Server/Server/API/Tool/Assets.Copy.cs
  Assets/root/Server/Server/API/Tool/Assets.Copy.cs.meta
  Assets/root/Server/Server/API/Tool/Assets.CreateFolders.cs
  Assets/root/Server/Server/API/Tool/Assets.CreateFolders.cs.meta
  Assets/root/Server/Server/API/Tool/Assets.Delete.cs
  Assets/root/Server/Server/API/Tool/Assets.Delete.cs.meta
  Assets/root/Server/Server/API/Tool/Assets.Move.cs
  Assets/root/Server/Server/API/Tool/Assets.Move.cs.meta
  Assets/root/Server/Server/API/Tool/Editor.Selection.Get.cs
  Assets/root/Server/Server/API/Tool/Editor.Selection.Get.cs.meta
  Assets/root/Server/Server/API/Tool/Editor.Selection.Set.cs
  Assets/root/Server/Server/API/Tool/Editor.Selection.Set.cs.meta
  Assets/root/Server/Server/API/Tool/Editor.Selection.cs
  Assets/root/Server/Server/API/Tool/Editor.Selection.cs.meta
  Assets/root/Server/Server/API/Tool/GameObject.Duplicate.cs
  Assets/root/Server/Server/API/Tool/GameObject.Duplicate.cs.meta
  Assets/root/Server/Server/API/Tool/GameObject.Select.cs
  Assets/root/Server/Server/API/Tool/GameObject.Select.cs.meta
  Assets/root/Server/Server/API/Tool/GameObject.SetParent.cs
  Assets/root/Server/Server/API/Tool/GameObject.SetParent.cs.meta
  Assets/root/Server/Server/API/Tool/Script.Delete.cs
  Assets/root/Server/Server/API/Tool/Script.UpdateOrCreate.cs
  Assets/root/Server/version
  README.md
Labels: enhancement

#88 Tool: Assets.Prefab.Create
  Assets/root/Documentation~/README.md
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.Create.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.Create.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.cs
  Assets/root/README.md
  Assets/root/Runtime/Utils/Serializer.GameObject.cs
  Assets/root/Server/Server/API/Tool/Assets.Prefab.Create.cs
  Assets/root/Server/Server/API/Tool/Assets.Prefab.Create.cs.meta
  Assets/root/Server/Server/API/Tool/GameObject.Find.cs
  Assets/root/package.json
  README.md
Labels: enhancement

#89 Tool: Assets.Prefab.Open + Assets.Prefab.Read
  Assets/root/Documentation~/README.md
  Assets/root/Editor/Scripts/API/Tool/Assets.Load.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.Close.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.Close.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.Create.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.Open.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.Open.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.Read.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.Read.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.Save.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.Save.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Assets.Prefab.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Search.cs
  Assets/root/Editor/Scripts/API/Tool/Editor.Selection.Get.cs
  Assets/root/Editor/Scripts/API/Tool/Editor.Selection.Set.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.AddComponent.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.Destroy.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.DestroyComponents.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.Duplicate.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.Find.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.GetComponents.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.ModifyComponent.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.SetParent.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.cs
  Assets/root/Editor/Scripts/Unity/GameObjectMetadata.cs
  Assets/root/Editor/Scripts/Unity/SceneMetadata.cs
  Assets/root/Editor/Scripts/Utils/GameObjectUtils.cs
  Assets/root/README.md
  Assets/root/Runtime/Utils/Serializer.Component.cs
  Assets/root/Runtime/Utils/Serializer.GameObject.cs
  Assets/root/Server/Common/Data/Unity/ComponentDataLight.cs
  Assets/root/Server/Common/Data/Unity/GameObjectDataLight.cs
  Assets/root/Server/Common/Data/Utils/InstanceId.cs
  Assets/root/Server/Common/Utils/Json/Converter/InstanceIdConverter.cs
  Assets/root/Server/Common/Utils/Json/JsonUtils.cs
  Assets/root/Server/Server/API/Tool/Assets.Load.cs
  Assets/root/Server/Server/API/Tool/Assets.Prefab.Close.cs
  Assets/root/Server/Server/API/Tool/Assets.Prefab.Close.cs.meta
  Assets/root/Server/Server/API/Tool/Assets.Prefab.Create.cs
  Assets/root/Server/Server/API/Tool/Assets.Prefab.Open.cs
  Assets/root/Server/Server/API/Tool/Assets.Prefab.Open.cs.meta
  Assets/root/Server/Server/API/Tool/Assets.Prefab.Read.cs
  Assets/root/Server/Server/API/Tool/Assets.Prefab.Read.cs.meta
  Assets/root/Server/Server/API/Tool/Assets.Prefab.Save.cs
  Assets/root/Server/Server/API/Tool/Assets.Prefab.Save.cs.meta
  Assets/root/Server/Server/API/Tool/Assets.Search.cs
  Assets/root/Server/Server/API/Tool/Editor.Selection.Get.cs
  Assets/root/Server/Server/API/Tool/Editor.Selection.Set.cs
  Assets/root/Server/Server/API/Tool/GameObject.AddComponent.cs
  Assets/root/Server/Server/API/Tool/GameObject.Destroy.cs
  Assets/root/Server/Server/API/Tool/GameObject.DestroyComponents.cs
  Assets/root/Server/Server/API/Tool/GameObject.Duplicate.cs
  Assets/root/Server/Server/API/Tool/GameObject.Find.cs
  Assets/root/Server/Server/API/Tool/GameObject.GetComponents.cs
  Assets/root/Server/Server/API/Tool/GameObject.ModifyComponent.cs
  Assets/root/Server/Server/API/Tool/GameObject.Select.cs
  Assets/root/Server/Server/API/Tool/GameObject.SetParent.cs
  Assets/root/Server/version
  Assets/root/package.json
  README.md
Labels: enhancement

#92 fix: GameObject.ModifyComponent
  Assets/root/Editor/Scripts/API/Tool/GameObject.ModifyComponent.cs
Labels: bug

#94 feat: Add primitive type parameter to GameObject creation methods
  Assets/root/Editor/Scripts/API/Tool/GameObject.Create.cs
  Assets/root/Server/Server/API/Tool/GameObject.Create.cs
Labels: bug, enhancement

#96 refactor: Tool GameObject.ModifyComponent + update: AI Connector window
  Assets/root/Editor/Scripts/API/Tool/Assets.Modify.cs
  Assets/root/Editor/Scripts/API/Tool/Assets.Modify.cs.meta
  Assets/root/Editor/Scripts/API/Tool/Assets.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.GetComponents.cs
  Assets/root/Editor/Scripts/API/Tool/GameObject.ModifyComponent.cs
  Assets/root/Editor/Scripts/UI/Window/MainWindowEditor.ClientConfigure.cs
  Assets/root/Editor/Scripts/UI/Window/MainWindowEditor.CreateGUI.cs
  Assets/root/Editor/UI/uxml/AiConnectorWindow.uxml
  Assets/root/Runtime/Utils/ReflectionUtils.Error.cs
  Assets/root/Runtime/Utils/ReflectionUtils.Error.cs.meta
  Assets/root/Runtime/Utils/ReflectionUtils.Unity.cs
  Assets/root/Runtime/Utils/ReflectionUtils.Unity.cs.meta
  Assets/root/Runtime/Utils/ReflectionUtils.cs
  Assets/root/Runtime/Utils/ReflectionUtils.cs.meta
  Assets/root/Server/Common/Data/Utils/SerializedMember.cs
  Assets/root/Server/Server/Hub/RemoteApp.cs
  Assets/root/Server/version
  Assets/root/package.json
Labels: bug, enhancement
