Repository IvanMurzak/Unity-MCP, pull requests merged in 2025-09, with the labels that each got.

#225 feature: Version increment script
  AssetStore-Installer/Packages/manifest.json
  AssetStore-Installer/Packages/packages-lock.json
  bump-version.ps1
  docs/version-management.md
Labels: enhancement

#251 Add UnixUtils for setting executable permissions
  Unity-MCP-Plugin/.vscode/settings.json
  Unity-MCP-Plugin/Assets/root/Editor/Scripts/Startup.Server.cs
  Unity-MCP-Plugin/Assets/root/Editor/Scripts/Utils/UnixUtils.cs
  Unity-MCP-Plugin/Assets/root/Editor/Scripts/Utils/UnixUtils.cs.meta
Labels: bug

#254 Update gitignore with Roo/Aider related values
  .gitignore
Labels: enhancement

#256 Update runtime temp content output dir to prevent unwanted artifacts
  Unity-MCP-Plugin/Assets/root/Runtime/Unity-MCP-Common/Directory.Build.props
  Unity-MCP-Plugin/Assets/root/Runtime/Unity-MCP-Common/Unity-MCP-Common.csproj
Labels: bug

#262 refactor: Documentation
  README.md
  Unity-MCP-Plugin/Assets/root/README.md
  docs/default-mcp-tools.md
  docs/mcp-server.md
Labels: documentation
